CPPFLAGS = -Wall

all:
	g++ -std=c++14 -o editor editor.cpp -lsfml-system -lsfml-graphics -lsfml-window

funcional:
	g++ -std=c++14 -o original original.cpp -lsfml-system -lsfml-graphics -lsfml-window